export const placeholders = {
    name: "Enter patient name",
    email: "Enter email address",
    phone: "Enter phone number",
    dateofbirth: "Select date of birth",
    gender: "Select gender",
    bloodgroup: "Select blood group",
    weight: "Enter weight in kg",
    height: "Enter height in cm",
    bmi: "BMI will be calculated",
    address: "Enter street address",
    city: "Enter city",
    state: "Enter state",
    country: "Enter country",
    pincode: "Enter PIN code",
    healthid: "Enter health ID",
    role: "User role",
  };
